In [2]:
import pandas as pd

In [5]:
cyber_global = pd.read_csv('../Global_Cybersecurity_Threats_2015-2024.csv')

In [6]:
cyber_indexes = pd.read_csv('../Cyber_security.csv')

In [12]:
cyber_global.head()

,Country,Year,Attack Type,Target Industry,Financial Loss (in Million $),Number of Affected Users,Attack Source,Security Vulnerability Type,Defense Mechanism Used,Incident Resolution Time (in Hours)
0,China,2019,Phishing,Education,80.53,773169,Hacker Group,Unpatched Software,VPN,63
1,China,2019,Ransomware,Retail,62.19,295961,Hacker Group,Unpatched Software,Firewall,71
2,India,2017,Man-in-the-Middle,IT,38.65,605895,Hacker Group,Weak Passwords,VPN,20
3,UK,2024,Ransomware,Telecommunications,41.44,659320,Nation-state,Social Engineering,AI-based Detection,7
4,Germany,2018,Man-in-the-Middle,IT,74.41,810682,Insider,Social Engineering,VPN,68

In [13]:
cyber_indexes.head()

       Country        Region    CEI    GCI   NCSI    DDL
0  Afghanistan  Asia-Pasific  1.000   5.20  11.69  19.50
1      Albania        Europe  0.566  64.32  62.34  48.74
2      Algeria        Africa  0.721  33.95  33.77  42.81
3      Andorra        Europe    NaN  26.38    NaN    NaN
4       Angola        Africa    NaN  12.99   9.09  22.69

In [14]:
cyber_loss = pd.read_csv('../LossFromNetCrime.csv')

In [15]:
cyber_loss.head()

,Country,2019_Complaints,2019_Losses,2020_Complaints,2020_Losses,2021_Complaints,2021_Losses,2022_Complaints,2022_Losses,2023_Complaints,2023_Losses,2024_Complaints,2024_Losses
0,PR,655,5929974,1338,7209755,1785,9463928,1594,17211758,1817,21018302,1974,31545772
1,PS,1784,22483591,2890,25423219,3352,48918464,3210,57796003,3378,69292891,3811,66002407
2,PT,1119,13870074,2020,12391290,2102,18205913,1918,30859319,2178,28700418,2209,40192274
3,PY,1913,10967865,2992,13815152,3188,26677869,3768,40114594,3487,33579643,2678,45168957
4,AE,5503,48101706,7390,81178182,10164,131934602,10042,187062157,11034,244238485,12071,280815215