In [1]:
import pandas as pd

In [4]:
cyber_loss = pd.read_csv("LossFromNetCrime.csv")

In [5]:
cyber_loss.head()

,Country,2019_Complaints,2019_Losses,2020_Complaints,2020_Losses,2021_Complaints,2021_Losses,2022_Complaints,2022_Losses,2023_Complaints,2023_Losses,2024_Complaints,2024_Losses
0,PR,655,5929974,1338,7209755,1785,9463928,1594,17211758,1817,21018302,1974,31545772
1,PS,1784,22483591,2890,25423219,3352,48918464,3210,57796003,3378,69292891,3811,66002407
2,PT,1119,13870074,2020,12391290,2102,18205913,1918,30859319,2178,28700418,2209,40192274
3,PY,1913,10967865,2992,13815152,3188,26677869,3768,40114594,3487,33579643,2678,45168957
4,AE,5503,48101706,7390,81178182,10164,131934602,10042,187062157,11034,244238485,12071,280815215

In [6]:
cyber_loss

,Country,2019_Complaints,2019_Losses,2020_Complaints,2020_Losses,2021_Complaints,2021_Losses,2022_Complaints,2022_Losses,2023_Complaints,2023_Losses,2024_Complaints,2024_Losses
0,PR,655,5929974,1338,7209755,1785,9463928,1594,17211758,1817,21018302,1974,31545772
1,PS,1784,22483591,2890,25423219,3352,48918464,3210,57796003,3378,69292891,3811,66002407
2,PT,1119,13870074,2020,12391290,2102,18205913,1918,30859319,2178,28700418,2209,40192274
3,PY,1913,10967865,2992,13815152,3188,26677869,3768,40114594,3487,33579643,2678,45168957
4,AE,5503,48101706,7390,81178182,10164,131934602,10042,187062157,11034,244238485,12071,280815215
...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,PE,4435,27363061,7339,27058091,8250,53418304,7956,76468535,9527,101727109,9251,91797172
113,PG,651,6153461,1016,6431254,1065,12315882,1073,18509434,1062,23087850,1353,27177455
114,PH,5688,179433874,10642,166452785,8192,276511773,11186,382348042,11365,534640287,12797,576134379
115,PK,28492,181705646,52024,200518146,40944,341893089,48572,681501827,53390,586037584,71700,786591645
116,PL,21903,390365695,42442,362788093,37317,596864046,48071,1207252948,49459,1040011485,40855,1359253205